apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: nginx-prod
namePrefix: prod-

resources:
  - ../../base
  - rollout.yaml
  - hpa.yaml

#patches:
#  - path: rollout-patch.yaml

#commonLabels:
#  environment: prod

labels:
  - pairs:
      environment: prod