apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: nginx-canary-error-rate
spec:
  metrics:
    - name: error-rate
      interval: 30s
      count: 4
      successCondition: result[0] < 5
      failureLimit: 1
      provider:
        prometheus:
          address: http://yace.monitoring.svc.cluster.local:80
          query: |
            sum(
              aws_applicationelb_httpcode_target_5_xx_count_sum
              * on(name) group_left(tag_ingress_k8s_aws_resource)
              aws_applicationelb_info{tag_ingress_k8s_aws_resource="nginx-dev/dev-nginx-dev-nginx-canary:80"}
            ) or vector(0)