apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: nginx-dev
namePrefix: dev-

resources:
  - ../../base
  - rollout.yaml
  - hpa.yaml
  - service-canary.yaml
  - ingress.yaml

#patches:
#  - path: rollout-patch.yaml

#commonLabels:
#  environment: dev

labels:
  - pairs:
      environment: dev