apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: nginx-environments
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions:
    - missingkey=error

  generators:
    - list:
        elements:
          - env: dev
            namespace: nginx-dev
            autoSync: true

          - env: prod
            namespace: nginx-prod
            autoSync: false

  template:
    metadata:
      name: 'nginx-{{ .env }}'
      labels:
        app.kubernetes.io/name: nginx
        app.kubernetes.io/part-of: platform-demo
        environment: '{{ .env }}'

    spec:
      project: platform

      source:
        repoURL: https://github.com/ppanchanathan/aws-terraform-platform.git
        targetRevision: main
        path: 'gitops/apps/nginx-kustomize/overlays/{{ .env }}'

      destination:
        server: https://kubernetes.default.svc
        namespace: '{{ .namespace }}'

      syncPolicy:
        {{- if .autoSync }}
        automated:
          prune: true
          selfHeal: true
        {{- end }}
        syncOptions:
          - CreateNamespace=true