apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: nginx-secret
  namespace: default
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secretsmanager
    kind: ClusterSecretStore
  target:
    name: nginx-secret
  data:
    - secretKey: username
      remoteRef:
        key: platform/dev/nginx
        property: username
    - secretKey: password
      remoteRef:
        key: platform/dev/nginx
        property: password