apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: alertmanager-slack
  namespace: monitoring
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secretsmanager
    kind: ClusterSecretStore
  target:
    name: alertmanager-slack
  data:
    - secretKey: webhook-url
      remoteRef:
        key: platform/dev/alertmanager-slack
        property: webhook-url