name: Platform Plan

on:
  pull_request:
    paths:
      - "platform/**"

permissions:
  id-token: write
  contents: read
  pull-requests: write

jobs:
  terraform-plan:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: hashicorp/setup-terraform@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: us-east-2
          role-to-assume: arn:aws:iam::240815058507:role/github-terraform-role

      - name: Terraform Init
        working-directory: platform/environments/dev
        run: terraform init -backend-config=backend.hcl

      - name: Terraform Format Check
        working-directory: platform/environments/dev
        run: terraform fmt -check -recursive

      - name: Terraform Validate
        working-directory: platform/environments/dev
        run: terraform validate

      - name: Terraform Plan
        working-directory: platform/environments/dev
        run: terraform plan
