# gitops/apps/prometheus-crds/kustomization.yaml

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - crds/alertmanagerconfigs.yaml
  - crds/alertmanagers.yaml

  - crds/podmonitors.yaml
  - crds/probes.yaml

  - crds/prometheusagents.yaml
  - crds/prometheuses.yaml
  - crds/prometheusrules.yaml

  - crds/scrapeconfigs.yaml
  - crds/servicemonitors.yaml

  - crds/thanosrulers.yaml
